### ISSUE TITLE
Broken Link to a Sample

### ISSUE THREAD

**Issue by asocorro** [Azure-Samples/azure-search-power-skills#136]
Hi, the link to a sample provided at the end of this document is broken:

Vector/EmbeddingGenerator/README.md

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Hello @asocorro thank you for reporting this. We have removed the broken link since no longer valid. If you need this functionality, please open a support case in https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request and ask for early access to this functionality. Thanks.
